# 統合版サーバーを起動させるコマンド
startCMD: "bedrock_server.exe"

#サーバー停止時、再起動時に ワールドをバックアップするかどうか
isBackup: false
#ワールドのパス
WorldPath: "./worlds/Bedrock level"
#ワールドのパス
WorldArchiveName: "./worlds/World-%Y-%m-%d-%H-%M-%S.mcworld"

#自動で再起動するかどうか
Reboot: true
#自動で再起動する時間
RebootTime: "05:00"

#指定した時間になったら設定したアクションを実行する機能を有効にするかどうか
ActionTimer: true
#時間とコマンドの設定
ActionTimerList:
  # time に 時間を記入
  # command に 実行したいコマンドを記入
  # say に チャットに表示したい文字

  # 難易度変更 easy
  - time: "50:30"
    say: "§rあと§e30§r分で難易度が§aイージー§rに変更されます"
  - time: "06:00"
    command: "difficulty easy"
  - time: "06:00"
    say: "§g難易度が§aイージー§gに変更されました"

  # 難易度変更 hard
  - time: "19:30"
    say: "§rあと§e30§r分で難易度が§cハード§rに変更されます"
  - time: "20:00"
    command: "difficulty hard"
  - time: "20:00"
    say: "§g難易度が§cハード§gに変更されました"

  # 時報
  - time: "00:00"
    say: "§6お知らせ 00時になりました"
  - time: "01:00"
    say: "§6お知らせ 01時になりました"
  - time: "02:00"
    say: "§6お知らせ 02時になりました"
  - time: "03:00"
    say: "§6お知らせ 03時になりました"
  - time: "04:00"
    say: "§6お知らせ 04時になりました"
  - time: "05:00"
    say: "§6お知らせ 05時になりました"
  - time: "06:00"
    say: "§6お知らせ 06時になりました"
  - time: "07:00"
    say: "§6お知らせ 07時になりました"
  - time: "08:00"
    say: "§6お知らせ 08時になりました"
  - time: "09:00"
    say: "§6お知らせ 09時になりました"
  - time: "10:00"
    say: "§6お知らせ 10時になりました"
  - time: "11:00"
    say: "§6お知らせ 11時になりました"
  - time: "12:00"
    say: "§6お知らせ 12時になりました"
  - time: "13:00"
    say: "§6お知らせ 13時になりました"
  - time: "14:00"
    say: "§6お知らせ 14時になりました"
  - time: "15:00"
    say: "§6お知らせ 15時になりました"
  - time: "16:00"
    say: "§6お知らせ 16時になりました"
  - time: "17:00"
    say: "§6お知らせ 17時になりました"
  - time: "18:00"
    say: "§6お知らせ 18時になりました"
  - time: "19:00"
    say: "§6お知らせ 19時になりました"
  - time: "20:00"
    say: "§6お知らせ 20時になりました"
  - time: "21:00"
    say: "§6お知らせ 21時になりました"
  - time: "22:00"
    say: "§6お知らせ 22時になりました"
  - time: "23:00"
    say: "§6お知らせ 23時になりました"
