# 統合版サーバーを起動させるコマンド
startCMD: "bedrock_server.exe"

#サーバー停止時、再起動時に ワールドをバックアップするかどうか
Backup: true
#ワールドのパス
WorldPath: "./worlds/Bedrock level"
#ワールドのバックアップファイルの形式
WorldArchiveFile: "./worlds/World-%Y-%m-%d-%H-%M-%S.mcworld"
#バックアップした時、バックアップファイルの数が数値以上になったら古いものから削除
# 0 に設定した場合は 削除しない
MaxBackupFile: 5

#自動で再起動するかどうか
Reboot: true
#自動で再起動する時間
RebootTime: "05:00"

#Webhookの機能を有効にするかどうか
Webhook: true
#WebhookのURL
WebhookURL: "http://localhost:5000"

#指定した時間になったら設定したアクションを実行する機能を有効にするかどうか
ActionTimer: true
#時間とコマンドの設定
ActionTimerList:
  # time に 時間を記入
  # command に 実行したいコマンドを記入
  # say に チャットに表示したい文字

  # 難易度変更 easy
  - time: "05:30"
    say: "§rあと§e30§r分で難易度が§aイージー§rに変更されます"
  - time: "06:00"
    command: "difficulty easy"
  - time: "06:00"
    say: "§g難易度が§aイージー§gに変更されました"

  # 難易度変更 hard
  - time: "19:30"
    say: "§rあと§e30§r分で難易度が§cハード§rに変更されます"
  - time: "20:00"
    command: "difficulty hard"
  - time: "20:00"
    say: "§g難易度が§cハード§gに変更されました"

  # 時報
  - time: "00:00"
    say: "§6お知らせ ０時になりました"
  - time: "01:00"
    say: "§6お知らせ １時になりました"
  - time: "02:00"
    say: "§6お知らせ ２時になりました"
  - time: "03:00"
    say: "§6お知らせ ３時になりました"
  - time: "04:00"
    say: "§6お知らせ ４時になりました"
  - time: "05:00"
    say: "§6お知らせ ５時になりました"
  - time: "06:00"
    say: "§6お知らせ ６時になりました"
  - time: "07:00"
    say: "§6お知らせ ７時になりました"
  - time: "08:00"
    say: "§6お知らせ ８時になりました"
  - time: "09:00"
    say: "§6お知らせ ９時になりました"
  - time: "10:00"
    say: "§6お知らせ １０時になりました"
  - time: "11:00"
    say: "§6お知らせ １１時になりました"
  - time: "12:00"
    say: "§6お知らせ １２時になりました"
  - time: "13:00"
    say: "§6お知らせ １３時になりました"
  - time: "14:00"
    say: "§6お知らせ １４時になりました"
  - time: "15:00"
    say: "§6お知らせ １５時になりました"
  - time: "16:00"
    say: "§6お知らせ １６時になりました"
  - time: "17:00"
    say: "§6お知らせ １７時になりました"
  - time: "18:00"
    say: "§6お知らせ １８時になりました"
  - time: "19:00"
    say: "§6お知らせ １９時になりました"
  - time: "20:00"
    say: "§6お知らせ ２０時になりました"
  - time: "21:00"
    say: "§6お知らせ ２１時になりました"
  - time: "22:00"
    say: "§6お知らせ ２２時になりました"
  - time: "23:00"
    say: "§6お知らせ ２３時になりました"
