# 統合版サーバーを起動させるコマンド
startCMD: "bedrock_server.exe"

#サーバー停止時、再起動時に ワールドをバックアップするかどうか
isBackup: false
#ワールドのパス
WorldPath: "./worlds/Bedrock level"
#ワールドのパス
WorldArchiveName: "./worlds/World-%Y-%m-%d-%H-%M-%S.mcworld"

#自動で再起動するかどうか
Reboot: true
#自動で再起動する時間
RebootTime: "06:00"

#指定した時間になったら設定したアクションを実行する機能を有効にするかどうか
ActionTimer: true
#時間とコマンドの設定
ActionTimerList:
  # time に 時間を記入
  # command に 実行したいコマンドを記入
  # say に チャットに表示したい文字

  - time: "20:00"
    command: "difficulty easy"

  - time: "20:46"
    command: "difficulty hard"

  - time: "20:46"
    say: "§r難易度が§cハード§rに変更されました"
